apiVersion: v1
kind: Service
metadata:
  name: hpa-example
  namespace: finastragpp
  labels:
        app: hpa-example
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http-port
    protocol: TCP
  selector:
    app: hpa-example
