apiVersion: v1
kind: Service
metadata:
  name: k8s-activemq-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: k8s-activemq

  ports:
    - name: http
      port: 8161
      nodePort: 32190
      
    - name: tcp
      port: 61616
      nodePort: 32191
  type: NodePort
