apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-configmap-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: hello-world-app-configmap

  ports:
    - name: http
      port: 8080
      nodePort: 30880

  type: NodePort

  